apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: rajeshargocd
  name: nginx-nodeport-service
  namespace: airflow
spec:
  ports:
    - nodePort: 30007
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: NodePort
